### PR TITLE
Install newt from deb package on Linux

### PR DESCRIPTION
**Pull request by utzig**
This avoids go get/install penalty and removes go dependency (I think!)

This supersedes #1

### CODE REVIEW

**Comment by michal-narajowski** [comment]
When testing your PR I got this error:
```
+[[ 0 -ne 0 ]]
/home/travis/ci/linux_travis_install.sh: 27: /home/travis/ci/linux_travis_install.sh: [[: not found
+dpkg -i newt_1.4.1-1_amd64.deb
dpkg: error: requested operation requires superuser privilege
```

While it would be nice to drop go dependency and simplify installation, I don't think Travis allows to install packages like this. We could set `sudo: true` and then install it with root privileges, but that would come with a price of not being able to use contenerized env (I think I forgot to add `sudo: false` and `dist: trusty` to enable it).

**Comment by utzig** [comment]
Ah, I was expecting `sudo: required` to be enabled! Will fix.

**Comment by michal-narajowski** [comment]
```
Container-based #
A fast boot time environment in which sudo commands are not available. Running Linux Ubuntu Trusty 14.04
```
https://docs.travis-ci.com/user/reference/overview/

I haven't done any comparison yet.

**Comment by utzig** [comment]
I don't think that is a big problem. The main disadvantage would be if changes are made to `newt` and the repository metadata which would invalidate the released .deb package. But this already happens on the current osx build anyway. Well, I'll close this one then.

**Pull request closed without merging**
